# Generated by Django 2.1.1 on 2018-09-20 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CsvFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('file_owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_owner_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CsvFileData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_header', models.CharField(max_length=255)),
                ('data', models.FloatField(blank=True, null=True)),
                ('row_num', models.IntegerField()),
                ('parent_file_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_file_id', to='mainsite.CsvFile')),
            ],
        ),
    ]
