# Generated by Django 2.1.1 on 2018-09-20 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_csvfile_csvfiledata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csvfile',
            name='file_owner_id',
        ),
        migrations.RemoveField(
            model_name='csvfiledata',
            name='parent_file_id',
        ),
        migrations.AddField(
            model_name='csvfile',
            name='file_owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='file_owner', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='csvfiledata',
            name='parent_file',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='parent_file', to='mainsite.CsvFile'),
            preserve_default=False,
        ),
    ]
