# Generated by Django 2.1.1 on 2018-09-20 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_auto_20180920_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvfiledata',
            name='column_num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
