# Generated by Django 2.1.1 on 2018-09-20 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0004_csvfiledata_column_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvfile',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
