# Generated by Django 2.1.1 on 2018-09-20 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0005_auto_20180920_2013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csvfile',
            old_name='name',
            new_name='display_name',
        ),
        migrations.AddField(
            model_name='csvfile',
            name='raw_name',
            field=models.CharField(default='name', max_length=255),
            preserve_default=False,
        ),
    ]
