# Generated by Django 2.1.1 on 2018-09-26 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0006_auto_20180920_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvfiledata',
            name='designation',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
