# Generated by Django 2.1.1 on 2018-09-27 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0008_mlmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csvfiledata',
            old_name='designation',
            new_name='type',
        ),
    ]
