# Generated by Django 2.1.1 on 2018-10-04 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0009_auto_20180927_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodel',
            name='parent_file',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='model_parent', to='mainsite.CsvFile'),
            preserve_default=False,
        ),
    ]
