# Generated by Django 2.1.2 on 2018-10-04 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0011_auto_20181004_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodel',
            name='type',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
