# Generated by Django 2.1.2 on 2018-10-04 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0012_mlmodel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodel',
            name='display_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
