# Generated by Django 2.1.2 on 2018-10-14 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0013_mlmodel_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodel',
            name='type_num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
