# Generated by Django 2.1.2 on 2018-10-14 18:37

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0014_mlmodel_type_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlmodel',
            name='data',
            field=picklefield.fields.PickledObjectField(editable=False),
        ),
    ]
