# Generated by Django 2.1.2 on 2018-11-01 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0015_auto_20181014_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodel',
            name='parameters',
            field=models.TextField(default='{}'),
            preserve_default=False,
        ),
    ]
