# Generated by Django 2.1.2 on 2018-11-08 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0016_mlmodel_parameters'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodel',
            name='accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='accuracy_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
