# Generated by Django 2.1.2 on 2018-11-29 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0017_auto_20181108_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvfiledata',
            name='placeholder',
            field=models.TextField(blank=True, null=True),
        ),
    ]
