class COLUMN_TYPE:
    IGNORE = 0
    INPUT = 1
    TARGET = 2

class ALGORITHM:
    LINEAR_REGRESSION = 1
    LOGISTIC_REGRESSION = 2
    LINEAR_DISCRIMINANT_ANALYSIS = 3
    REGRESSION_TREES = 4
    NAIVE_BAYES = 5
    RANDOM_FOREST = 6
    K_NEAREST_NEIGHBORS = 7
    SUPPORT_VECTOR_MACHINES = 8
    NEAREST_CENTROID = 9
